name: Build
on: [push]

jobs:
  build:
    # TODO: build for ARM Linux.
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]

    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v13
        with:
          name: ovyerus
          authToken: ${{ secrets.CACHIX_API_KEY }}

      - run: nix build .#all -L --cores 4
      - run: nix build .#tar -L
